baseURL = "https://joncourbon.github.io/ecofriendly_website/"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Towards eco-friendly websites !"
theme = "beautifulhugo"

metaDataFormat = "yaml"
publishDir = "docs"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = true
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false

[Params]
  #homeTitle = "Hugo and eco-friendly websites" # Set a different text for the header on the home page
  subtitle = "Experiments to build an eco-friendly website"
  mainSections = ["post","posts"]
  logo = "img/logo.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = false
  useHLJS = false
  socialShare = true
#  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  publishDir="docs"

[Author]
  name = "Jonathan Courbon"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
#  facebook = "username"
  github = "JonCourbon"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
  linkedin = "courbonjonathan"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "ressources"
    name = "Ressources"
    url="ressources/"
    weight = 2

[[menu.main]]
    identifier = "coding"
    name = "Coding"
    url = "ressources/coding"
    parent = "ressources"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4

